# Generated by Django 3.2.8 on 2021-10-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20211023_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
    ]
